config/routes.rb
Rails.application.routes.draw do
  root to: "lists#index"
  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, presence: true
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      flash[:notice] = "Bookmark created successfully."
      redirect_to list_path(@list)
    else
      flash[:error] = "Error creating bookmark."
      render :action => 'new'
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    flash[:notice] = "Bookmark deleted successfully."
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1 class="playlist_and_bookmark_title"><%= @list.name.upcase %></h1>

<div class="bookmark_form">
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment, :placeholder => 'Add a comment' %>
    <%= f.association :movie, input_html: { id: "selection" }, prompt: "Select a movie" %>
    <%= f.button :submit, class: "btn btn-success" %>
    <%= link_to 'Back to the list', list_path(@list), class: " btn btn-warning" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<h1 class="playlist_and_bookmark_title">Your new playlist</h1>

<div class="new_playlist_form">
  <%= simple_form_for(@list) do |f| %>
    <%= f.input :name %>
    <p style="color:white;">Playlist name</p>

    <%= f.input :photo, as: :file %>
    <%= f.button :submit, class: "btn btn-success" %>
    <%= link_to "Back to lists", root_path, class: "btn btn-warning" %><br>
  <% end %>
</div>

app/views/lists/index.html.erb
<div class = "banner">
  <h1>Lists</h1>
  <h2><%= link_to "Create a movie list", new_list_path, class: "btn btn-primary" %></h2>
</div>

<div class="cards">
  <div class="row">
    <% @lists.each do |list| %>

      <div class="card" col-6 col-md-9 col-lg-12>
        <div class="card_img">
          <%= link_to list_path(list) do %>
            <% if list.photo.attached? %>
              <%= cl_image_tag(list.photo.key) %>
            <% else %>
              <%= list.name %>
            <% end %>
          <% end %>
        </div>
          <h2><strong><%= list.name.upcase %></strong></h2>
        </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<h1>New Playlist</h1>

<%= render "form", list: @list %>

app/views/lists/show.html.erb
<div class="playlist_and_bookmark_title">
  <h1><%= @list.name.upcase %></h1>
</div>

<div class="movies_container">
  <div class="row">
      <% @list.bookmarks.each do |bookmark| %>
        <div class="movie" col-12 col-lg-6>

          <div class="movie_img">
            <%= image_tag bookmark.movie.poster_url, :height=>250, class: "imgstyle", :crop=>"scale"%>
          </div>

          <div class="movie_text">
            <div class="movie_title_rating">
              <strong><%= bookmark.movie.title %></strong><%= bookmark.movie.rating %> &#11088<br><br>
            </div>
            <%= bookmark.movie.overview %><br><br>

            Your Comment : <%= bookmark.comment %><br>

            <%= link_to "Delete the movie", bookmark_path(bookmark),
                    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
                    color: $FD1015%>
          </div>
        </div>
      <% end %>
  </div>
</div>

<div>

<div class="playlist_btns">
  <%= link_to "Add a bookmark to this list", new_list_bookmark_path(@list), class: "btn btn-primary"%>
  <%= link_to "Back to playlists", root_path, class: "btn btn-success" %><br>

  <%= link_to "Delete the playlist", list_path(@list),
      data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
      class: "btn btn-warning" %>
</div>